# Author: Xing Szen

class MongoDBQuerier:
    
    def __init__(self, db_connector):
        self.db_connector = db_connector

    def get_comprehensive_risk_analysis(self, base_col, receivers_col, iptakeover_col):
        # Retrieve the main PotentialOffenders collection to act as our base table
        collection = self.db_connector.get_collection(base_col)
        
        pipeline = [
            # 1. Cast string fields to numbers so we can perform math on them
            {
                "$addFields": {
                    "num_velocity": {"$toDouble": "$velocity_score"},
                    "num_geo": {"$toDouble": "$geo_anomaly_score"},
                    "num_amount": {"$toDouble": "$amount"}
                }
            },
            # 2. Join the SuspiciousReceivers collection (LEFT JOIN)
            {
                "$lookup": {
                    "from": receivers_col,
                    "localField": "receiver_account",
                    "foreignField": "receiver_account",
                    "as": "receiver_data"
                }
            },
            # 3. Join the IpTakeover collection (LEFT JOIN)
            {
                "$lookup": {
                    "from": iptakeover_col,
                    "localField": "ip_address",
                    "foreignField": "ip_address",
                    "as": "ip_data"
                }
            },
            # 4. Create boolean flags to see if the joins found anything, 
            # and calculate a "Base Risk" formula: velocity + (geo_anomaly * 20)
            {
                "$addFields": {
                    "receiver_flag": {"$gt": [{"$size": "$receiver_data"}, 0]},
                    "ip_flag": {"$gt": [{"$size": "$ip_data"}, 0]},
                    "base_risk": {"$add": ["$num_velocity", {"$multiply": ["$num_geo", 20]}]}
                }
            },
            # 5. Calculate the Final Composite Score and assign a Threat Level String
            {
                "$addFields": {
                    "composite_risk_score": {
                        "$add": [
                            "$base_risk",
                            # If they are a known suspicious receiver, add 50 to the risk score
                            {"$cond": [{"$eq": ["$receiver_flag", True]}, 50, 0]},
                            # If they are from a compromised IP, add 50 to the risk score
                            {"$cond": [{"$eq": ["$ip_flag", True]}, 50, 0]}
                        ]
                    },
                    "threat_level": {
                        "$switch": {
                            "branches": [
                                # If they matched multiple tables, they are critical
                                {"case": {"$or": ["$receiver_flag", "$ip_flag"]}, "then": "CRITICAL (MULTI-VECTOR)"},
                                # If their base score is unusually high, flag as High
                                {"case": {"$gte": ["$base_risk", 35]}, "then": "HIGH (ANOMALY)"}
                            ],
                            "default": "ELEVATED (VELOCITY)"
                        }
                    }
                }
            },
            # 6. Sort by the highest Composite Risk Score so the worst offenders are at the top
            {
                "$sort": {"composite_risk_score": -1}
            },
            # 7. Limit to top 15 for a clean screenshot in your report
            {
                "$limit": 15
            },
            # 8. Clean up the output columns for Spark
            {
                "$project": {
                    "_id": 0,
                    "sender_account": 1,
                    "receiver_account": 1,
                    "ip_address": 1,
                    "amount": 1,
                    "threat_level": 1,
                    "composite_risk_score": {"$round": ["$composite_risk_score", 2]},
                    "receiver_flag": 1,
                    "ip_flag": 1
                }
            }
        ]
        
        return list(collection.aggregate(pipeline))

    def get_dynamic_risk_profiles(self, collection_name, min_volume=1000):
        # Retrieve the FraudProfiles collection generated by the batch layer
        collection = self.db_connector.get_collection(collection_name)
        
        pipeline = [
            # Filter out transaction types that don't have enough volume to be statistically significant
            {
                "$match": {
                    "total_count": {"$gte": min_volume}
                }
            },
            # $switch acts like an IF-ELSE IF-ELSE statement.
            # We assign a risk category based on the fraud percentage threshold.
            {
                "$addFields": {
                    "risk_category": {
                        "$switch": {
                            "branches": [
                                {"case": {"$gte": ["$fraud_percentage", 4.0]}, "then": "CRITICAL"},
                                {"case": {"$gte": ["$fraud_percentage", 3.6]}, "then": "HIGH"}
                            ],
                            "default": "MODERATE"
                        }
                    }
                }
            },
            # Only return the transaction types that are classified as CRITICAL or HIGH risk
            {
                "$match": {
                    "risk_category": {"$in": ["CRITICAL", "HIGH"]}
                }
            },
            # Sort the most dangerous ones to the top
            {
                "$sort": {"fraud_percentage": -1}
            },
            # Clean up the final output columns
            {
                "$project": {
                    "_id": 0,
                    "transaction_type": 1,
                    "total_count": 1,
                    "fraud_percentage": 1,
                    "risk_category": 1
                }
            }
        ]
        
        return list(collection.aggregate(pipeline))